### ISSUE TITLE
上报间隔传参问题

### ISSUE THREAD

**Issue by BeWaterMF** [luojilab/DataReporter#2]
![image](https://user-images.githubusercontent.com/18167587/68943123-41bc8300-07e5-11ea-8582-3ed237831b53.png)
demo里写的10秒间隔传的是10，我怎么觉得是传10*1000呢，是我哪个地方没注意到吗

**Comment by lixiaoyu0123** [comment]
确实是毫秒，10秒应该是10*1000 才对，demo单位写错了。感谢反馈。 使用过程有任何问题都可以反馈上来，感谢。
