### ISSUE TITLE
数据不上报问题

### ISSUE THREAD

**Issue by BeWaterMF** [luojilab/DataReporter#3]
我push了很多条数据，却一直不会走到upload回调，不知道是什么情况？和我这边是多进程APP有关吗，reporter的实例化是放在Application的onCreate（）中做的

**Comment by lixiaoyu0123** [comment]
跟多进程没有关系，DataReporter的方法调用，都要放在ui线程，不要担心性能问题，DataReporter直接写入内存buf，另一个线程在处理调度，不会产生任何性能问题和ui block的风险。如果不是在ui线程调用，会接不到回调的。麻烦检查下是否在ui线程调用。

**Comment by BeWaterMF** [comment]
是在主线程调用的

**Comment by BeWaterMF** [comment]
![image](https://user-images.githubusercontent.com/18167587/69507788-b1153e00-0f6e-11ea-9fc7-976c6766d0a2.png)
application里的onCreate（）里这么写的，会出现我上面写的那个问题，如果加上仅主进程才进行这些操作的话，是OK的

**Comment by lixiaoyu0123** [comment]
上面的post没理解是什么目的， 直接DataReporter的构建 在Application的onCreat方法中就好了，可以做一个简单的封装。
针对多进程的问题， 如果需要多进程使用，需要根据进程id构建不同的进程实例，同时要保证缓存路径是不同的。 多进程的上报都是独立的。不会相互影响。

**Comment by BeWaterMF** [comment]
post的目的是保证在主线程调用，这段代码的调用时机不是由我这边决定的；
区分进程创建不同reporter实例后，确实没有再出现上述的异常问题。
