### ISSUE TITLE
armeabi libdata-reporter.so

### ISSUE THREAD

**Issue by hprostudy** [luojilab/DataReporter#5]
因项目仅支持armeabi下so，请问armeabi-v7a 下so可以放入armeabi下吗？  或者提供下armeabi so
谢谢

**Comment by lixiaoyu0123** [comment]
拉取最新代码，使用ndk16（包含16）及以下版本编译，同时把build/Android/datareporter/build.gradle中的提到'armeabi-v7a', 'arm64-v8a'前面加上'armeabi', 因为ndk18以后版本不再支持armeabi，所以不在本项目代码中进行修改，需要armeabi的用户，麻烦自己修改编译。
