### ISSUE TITLE
爆内存的风险

### ISSUE THREAD

**Issue by zhencang** [luojilab/DataReporter#6]
发送速度跟不上产生数据的速度，这个时候内存一直在涨，长时间下来有可能爆内存。

**Comment by lixiaoyu0123** [comment]
你是android 还是iOS上出现这种问题？

**Comment by lixiaoyu0123** [comment]
生产速度过快，多余的数据会落盘，不会爆内存

**Comment by zhencang** [comment]
iOS 哦

**Comment by zhencang** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/26265177/77134422-dee43c80-6aa1-11ea-9355-2063b4830fef.png">

**Comment by zhencang** [comment]
莫非是使用姿势不对😂

**Comment by lixiaoyu0123** [comment]
我们这边又进行了复测，还是没有出现你上图的情况，麻烦能问下你上图使用的应用是sample，还是你自己的App，另外，能麻烦提供更多的数据吗？是否还会继续增涨，知道内存爆掉。 还是会稳定在70多M？

**Comment by zhencang** [comment]
会一直涨，没有顶，用的是sample里面的代码，加上了自己的上报网络请求。

**Comment by lixiaoyu0123** [comment]
我们复查，找到了问题，是因为我们cmake配置中没有配置ARC导致 oc的内存泄漏。 用xcode编译默认是开启的，所以我们在用xcode编译时候是未复现问题的，最新的配置cmake已经增加ARC配置，并验证内存稳定住了。 感谢反馈，有任何问题，欢迎再反馈。

**Comment by lixiaoyu0123** [comment]
> 莫非是使用姿势不对😂

我们复查，找到了问题，是因为我们cmake配置中没有配置ARC导致 oc的内存泄漏。 用xcode编译默认是开启的，所以我们在用xcode编译时候是未复现问题的，最新的配置cmake已经增加ARC配置，并验证内存稳定住了。 感谢反馈，有任何问题，欢迎再反馈。
