### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by skyammk** [luojilab/DataReporter#7]
使用Kotlin代码实例化mDataReporter的时候报错。

使用这行代码实例化：
`mDataReporter = DataReporter.makeDataReporter(uuid, applicationContext.filesDir.path, key, reportImp)`

报错信息如下：
`java.lang.UnsatisfiedLinkError: No implementation found for long com.iget.datareporter.DataReporter.makeReporter(java.lang.String, java.lang.String, java.lang.String, com.iget.datareporter.IReport) (tried Java_com_iget_datareporter_DataReporter_makeReporter and Java_com_iget_datareporter_DataReporter_makeReporter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Lcom_iget_datareporter_IReport_2)
        at com.iget.datareporter.DataReporter.makeReporter(Native Method)
        at com.iget.datareporter.DataReporter.<init>(DataReporter.java:82)
        at com.iget.datareporter.DataReporter.makeDataReporter(DataReporter.java:37)`

gradle是这样引入的：
`api 'com.luojilab.component:datareporter:1.3.8'`

未做代码混淆

**Comment by skyammk** [comment]
版本号是1.3.8，未做代码混淆

**Comment by lixiaoyu0123** [comment]
我们测试了kotlin环境，没有复现你反馈的问题， 能提供下gradle配置吗？

**Comment by skyammk** [comment]
您说的Gradle配置具体是指哪部分代码？
另外方便给一个联系方式么。。我这边需求比较急。。

**Comment by skyammk** [comment]
应该是我加了
`ndk {
    abiFilters 'armeabi', 'x86'
}`
导致的。删了之后就好了
